runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  #APP_ENV: production
  APP_LOG: errorlog
  APP_KEY: base64:cH8P4mjLvZNZ2ie+F/GKIOMXwAzPEyFjDJTu9Q7FWKA=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  APP_TIMEZONE: UTC #your timezone of choice


  # follow the part of the tutorial on setting up your SQL database
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: mangaseries_db
  DB_USERNAME: mangaseries
  DB_PASSWORD: mangaseries
  DB_SOCKET: "/cloudsql/mngseriescom:us-central1:mangaseries-today-database"

  QUEUE_DRIVER: database #in case you execute queued jobs

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525
  MAIL_USERNAME: 502d880e0a1606
  MAIL_PASSWORD: 35f58117e9cb7e

  #LOG_DELETE:  true # this is a parameter added by us in the project .env file. You can add here any setting you would add to your .env file

  #GOOGLE_VISION_PROJECT_ID : mngseriescom

#we need this for the flex environment
beta_settings:
   # for Cloud SQL, set this value to the Cloud SQL connection name,
   # e.g. "project:region:cloudsql-instance"
   cloud_sql_instances: "mngseriescom:us-central1:mangaseries-today-database"

liveness_check:
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5

readiness_check:
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5
  app_start_timeout_sec: 30000
